### PR TITLE
change build_dir

### PR DESCRIPTION
**Pull request by sunheyi6**
If you use docs, you will find that the dist folder cannot be found.
Close https://github.com/vuepress/vuepress-next/pull/1444

### CODE REVIEW

**Comment by sunheyi6** [comment]
> Could you explain more? Our current workflow is working well: https://github.com/vuepress/docs/actions/workflows/docs.yml

This is not the same thing, mine is deployed on Vercel, while yours is deployed on GitHub Pages

**Comment by meteorlxy** [comment]
So why you update our deployment according to yours?

**Comment by Mister-Hope** [comment]
I need the full log, i.e. 71 lines and your repo

**Comment by sunheyi6** [comment]
> I need the full log, i.e. 71 lines and your repo
repo:https://github.com/sunheyi6/mydocs  The current production uses src. If the docs deployment fails, it will not be updated to production.
log:
[14:08:47.848] Running build in Washington, D.C., USA (East) – iad1
[14:08:47.985] Cloning github.com/sunheyi6/mydocs (Branch: master, Commit: b4e381b)
[14:08:48.006] Skipping build cache, deployment was triggered without cache.
[14:08:48.627] Cloning completed: 642.28ms
[14:08:48.998] Running "vercel build"
[14:08:49.558] Vercel CLI 32.6.1
[14:08:50.334] Detected `pnpm-lock.yaml` version 6 generated by pnpm 8
[14:08:50.346] Installing dependencies...
[14:08:52.116] Lockfile is up to date, resolution step is skipped
[14:08:52.205] Progress: resolved 1, reused 0, downloaded 0, added 0
[14:08:52.411] Packages: +606
[14:08:52.412] ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
[14:08:53.207] Progress: resolved 606, reused 0, downloaded 14, added 3
[14:08:54.207] Progress: resolved 606, reused 0, downloaded 64, added 64
[14:08:55.208] Progress: resolved 606, reused 0, downloaded 121, added 120
[14:08:56.210] Progress: resolved 606, reused 0, downloaded 164, added 159
[14:08:57.211] Progress: resolved 606, reused 0, downloaded 216, added 216
[14:08:58.212] Progress: resolved 606, reused 0, downloaded 255, added 255
[14:08:59.212] Progress: resolved 606, reused 0, downloaded 261, added 261
[14:09:00.213] Progress: resolved 606, reused 0, downloaded 264, added 264
[14:09:01.214] Progress: resolved 606, reused 0, downloaded 266, added 266
[14:09:03.654] Progress: resolved 606, reused 0, downloaded 267, added 266
[14:09:04.656] Progress: resolved 606, reused 0, downloaded 270, added 270
[14:09:05.657] Progress: resolved 606, reused 0, downloaded 271, added 271
[14:09:06.657] Progress: resolved 606, reused 0, downloaded 277, added 277
[14:09:07.657] Progress: resolved 606, reused 0, downloaded 285, added 285
[14:09:08.659] Progress: resolved 606, reused 0, downloaded 297, added 297
[14:09:09.659] Progress: resolved 606, reused 0, downloaded 327, added 327
[14:09:10.659] Progress: resolved 606, reused 0, downloaded 368, added 368
[14:09:11.660] Progress: resolved 606, reused 0, downloaded 420, added 419
[14:09:12.661] Progress: resolved 606, reused 0, downloaded 468, added 466
[14:09:13.662] Progress: resolved 606, reused 0, downloaded 522, added 522
[14:09:14.663] Progress: resolved 606, reused 0, downloaded 575, added 574
[14:09:15.663] Progress: resolved 606, reused 0, downloaded 604, added 604
[14:09:17.761] Progress: resolved 606, reused 0, downloaded 605, added 604
[14:09:18.762] Progress: resolved 606, reused 0, downloaded 605, added 605
[14:09:20.811] Progress: resolved 606, reused 0, downloaded 606, added 605
[14:09:20.813] Progress: resolved 606, reused 0, downloaded 606, added 606, done
[14:09:21.126] .../node_modules/vue-demi postinstall$ node ./scripts/postinstall.js
[14:09:21.846] .../node_modules/vue-demi postinstall: Done
[14:09:21.857] .../esbuild@0.19.8/node_modules/esbuild postinstall$ node install.js
[14:09:21.930] .../esbuild@0.19.8/node_modules/esbuild postinstall: Done
[14:09:22.061] 
[14:09:22.061] devDependencies:
[14:09:22.061] + @vuepress/client 2.0.0-rc.0
[14:09:22.061] + vue 3.3.9
[14:09:22.061] + vuepress 2.0.0-rc.0
[14:09:22.062] + vuepress-theme-hope 2.0.0-rc.1
[14:09:22.062] 
[14:09:22.062] The dependency was already listed in devDependencies.
[14:09:22.062] If you want to make it a prod dependency, then move it manually.
[14:09:22.062] 
[14:09:22.065] Done in 31.6s
[14:09:22.560] 
[14:09:22.560] > vuepress-theme-hope-template@2.0.0 docs:build /vercel/path0
[14:09:22.560] > vuepress build src
[14:09:22.560] 
[14:09:24.243] - Initializing and preparing data
[14:09:24.696] ✔ Initializing and preparing data - done in 453ms
[14:09:24.697] - Compiling with vite
[14:09:33.285] ✔ Compiling with vite - done in 8.59s
[14:09:33.286] - Rendering 13 pages
[14:09:33.372] [Vue warn]: Invalid vnode type when creating vnode: undefined.
[14:09:33.673] ✔ Rendering 13 pages - done in 387ms
[14:09:33.677] - Generating robots.txt
[14:09:33.678] [34mvuepress-plugin-seo2: [39m ✔ Generating robots.txt
[14:09:33.679] - Generating sitemap to [36m/sitemap.xml[39m
[14:09:33.688] [34mvuepress-plugin-sitemap2: [39m ✔ Generating sitemap to [36m/sitemap.xml[39m
[14:09:33.689] - Appended sitemap path to [36mrobots.txt[39m
[14:09:33.691] [34mvuepress-plugin-sitemap2: [39m ✔ Appended sitemap path to [36mrobots.txt[39m
[14:09:33.692] [32msuccess[39m VuePress build completed in 10.42s!
[14:09:33.753] Error: No Output Directory named "dist" found after the Build completed. You can configure the Output Directory in your Project Settings.
[14:09:33.754] Learn More: https://vercel.link/missing-public-directory
[14:09:34.099]

**Comment by Mister-Hope** [comment]
Tell me why there should be `docs/.vuepress/dist` when you use `src` folder ?

**Pull request closed without merging**
